AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  snap-accelerate

  Sample SAM Template for snap-accelerate

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloSnapFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      # 函数源代码路径
      CodeUri: snap-accelerate
      # 函数入口：对应src/main/java/helloSnap/App.java 中的handleRequest方法，格式为 packageName.className::methodName
      Handler: helloSnap.App::handleRequest
      # 函数名称
      FunctionName: hello-snap
      # Lambda SnapStart 目前(2024/04/08)只支持Java 11及以上版本
      Runtime: java17
      # 设置内存大小
      MemorySize: 512
      # Lambda SnapStart 目前(2024/04/08)支持的CPU架构只有x86_64
      Architectures:
        - x86_64
      # 为java项目开启Lambda SnapStart
      SnapStart:
        ApplyOn: PublishedVersions
      # 开启Lambda SnapStart必须先开version或者alias: You can use SnapStart only on published function versions and aliases that point to versions
      AutoPublishAlias: live
      # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Environment:
        Variables:
          java_version: java17
      Events:
        HelloSnap:
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            Path: /snap
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloSnapApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello Snap function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/snap/"
  HelloSnapFunction:
    Description: "Hello Snap Lambda Function ARN"
    Value: !GetAtt HelloSnapFunction.Arn
  HelloSnapFunctionIamRole:
    Description: "Implicit IAM Role created for Hello Snap function"
    Value: !GetAtt HelloSnapFunctionRole.Arn
