# 参考链接: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "location-service"

[default.build.parameters]
cached = false
parallel = true
# 使用容器环境构建项目
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
# 使用具体的S3桶
s3_bucket = 'thinktik-poc-devops'
# 使用具体的S3桶内路径
s3_prefix = 'lambda-deploy/sam-framework'

[default.package.parameters]
resolve_s3 = false

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
