AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  local-dev-python

  local develop aws lambda project with python 3.12

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # 函数超时时间值
    Timeout: 3

Resources:
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [ LocalDevFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${LocalDevFunction}
      RetentionInDays: 7

  LocalDevFunction:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      Role: "arn:aws:iam::843245141269:role/poc-lambda-role"
      VpcConfig:
        SecurityGroupIds:
          - sg-0f535b902427074e7
        SubnetIds:
          - subnet-04fcf4683c6a14b4d
          - subnet-03f68e34e9d2f87f0
          - subnet-081ba9c36f1afbc3d
      # 代码的src文件夹路径
      CodeUri: src/
      # 本次lambda函数的位置
      Handler: app.lambda_handler
      # 函数名称
      FunctionName: local-dev-python
      # 自动创建alias别名
      AutoPublishAlias: live
      # 函数运行时(语言+版本)
      Runtime: python3.12
      # 运行时底层的CPU架构，可选的值为x86_64或者arm64
      Architectures:
        - arm64
      # 触发Lambda运行的Event集合
      Events:
        # 第一个event，一个api-gateway event
        LocalDev:
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            # http request url path
            Path: /hello
            # http request method
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LocalDevApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

